### PR TITLE
Include the full discovery url on invalid HTTP response

### PR DESCRIPTION
**Pull request by Timshel**
Hey,

Simple PR to add the full discovery url to the error since in lot of cases it will be due to an improper `issuer_url`.

### CODE REVIEW

**Comment by ramosbugs** [comment]
Thanks for the PR! I'll merge once CI passes (looks like `cargo fmt` is unhappy)

**Comment by Timshel** [comment]
O yes sorry :)

**Comment by Timshel** [comment]
I had tried running it and it failed so I invalidly concluded that you did not use it.
On another project it's included in the `rust-toolchain.toml`.

But I'm a bit of a rust noob so not sure of the best practices :).

**Comment by ramosbugs** [comment]
Thanks!

> I had tried running it and it failed so I invalidly concluded that you did not use it.

When I run it locally with Cargo/Rust 1.71.0 (`rustfmt 1.5.2-stable`), it doesn't seem to change any of the formatting. Is it possible you ran it with the nightly toolchain?

> On another project it's included in the `rust-toolchain.toml`.

I think this file is mainly for pinning to specific versions: https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file.

**Comment by ramosbugs** [comment]
This is now released in [3.5.0](https://crates.io/crates/openidconnect/3.5.0).

**Pull request merged**
