### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by Erik1000**
I wanted to contribute to this crate (#68) and while attempting to do so, rust-analyzer (with clippy) complaint. I thought, I could use this chance to fix the clippy errors and do some clean up.

### CODE REVIEW

**Comment by Erik1000** [comment]
CI fails because of ring (https://github.com/rust-lang/rust/issues/95267)

**Comment by ramosbugs** [comment]
Thanks for the cleanup! I'll take a look once nightly gets fixed (sounds like early next week). My main concern about fixing clippy lints is that newer versions of clippy may suggest changes involving newer language features that break compatibility with the MSRV 1.45.0. As long as CI passes, the changes should be fine though.

Also, feel free to add [`fail-fast: false`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast) to the GitHub Actions job if you don't want to wait for the nightly fix. I think if I add that to the `main` branch right now it won't get pulled in unless you merge or rebase.

**Comment by Erik1000** [comment]
```rust
error: use of `unwrap_or` followed by a function call
  --> src/http_utils.rs:17:31
   |
17 |             ct[..ct.find(';').unwrap_or(ct.len())].to_lowercase() == expected_essence.to_lowercase()
   |                               ^^^^^^^^^^^^^^^^^^^ help: try this: `unwrap_or_else(|| ct.len())`
   |
   = note: `-D clippy::or-fun-call` implied by `-D warnings`
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#or_fun_call
   ```

We now have the situation that the clippy version from MSVC does not recognize that `ct.len()` is a const function (it is since 1.39, MSVC is 1.45) and therefore thinks that this is `unwrap_or` with a function call. The latest clippy however does recognize that and warns when using `unwrap_or_else` since it is not needed:
```rust
warning: unnecessary closure used to substitute value for `Option::None`
  --> src/http_utils.rs:17:18
   |
17 |             ct[..ct.find(';').unwrap_or_else(|| ct.len())].to_lowercase()
   |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use `unwrap_or` instead: `ct.find(';').unwrap_or(ct.len())`
   |
   = note: `#[warn(clippy::unnecessary_lazy_evaluations)]` on by default
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_lazy_evaluations
```

Using `unwrap_or` is -- no matter the compiler version -- the right choice, but what should we do about the false positive with the old clippy version?

**Comment by Erik1000** [comment]
Related to https://github.com/rust-lang/rust-clippy/issues/6943

**Comment by ramosbugs** [comment]
I think let's go with `unwrap_or` and annotate the line with `#[allow(clippy::or_fun_call)]` so that clippy 1.45.0 doesn't complain. that should make CI happy (other than the known ring issue on nightly).

**Comment by ramosbugs** [comment]
thanks!

**Pull request merged**
