### PR TITLE
Bump ring to 0.16

### PR DESCRIPTION
**Pull request by dfaust**
Update ring to version 0.16.

I haven't used ring before, so you may want to review this PR with care.

### CODE REVIEW

**Comment by ramosbugs** [comment]
Thanks for the PR! Unfortunately, I need to keep this crate compatible with the latest version of [`rocket_http`](https://crates.io/crates/rocket_http), which depends on ring 0.14. If https://github.com/briansmith/ring/pull/849 ever merges upstream, then we can safely upgrade the ring dependency in this crate without breaking interoperability with Rocket.

**Comment by dfaust** [comment]
Yeah, that's fine. I'm experimenting with the Rocket async branch.

**Comment by jlindsey** [comment]
@ramosbugs Latest `rocket_http` (`0.4.4`) uses `ring = "^0.16.0"` (or rather the dependent `cookie` crate does). Any chance of getting this merged or are you still waiting for your ring PR?

**Comment by UkonnRa** [comment]
+1, Any update?

**Pull request merged**
