### PR TITLE
Migrating to new oauth4 version

### PR DESCRIPTION
**Pull request by mettke**
(Build failure expected)

This time separating is a bit difficult so its all combined into one. 

* Removed future-01
* Removed reqwest-09
* Updated http to 0.2
* Updated dev dependencies to latest version

When you release oauth2 and switch openidconnect-rs to version 4 remember to set `default-features = false` ;)

### CODE REVIEW

**Comment by mettke** [comment]
@Weasy666 with the release its now possible to get this merged. Would be nice if you rebase yours so that we can get them in one after the other. Also I had to add a few Send + Sync to satisfy Fail. If possible it would be awesome if you can remove them again in your change.

**Comment by mettke** [comment]
@ramosbugs Ready to merge once it compiles.

**Comment by Weasy666** [comment]
Sure, will take a look at it and rebase it later at the day.

**Comment by ramosbugs** [comment]
thank you both! appreciate the collaboration 😄

**Pull request merged**
